config/routes.rb
Rails.application.routes.draw do

  root :controller => 'user', :action => 'login'
  resources :grading_levels
  resources :ranking_levels, :collection => {:create_ranking_level=>[:get,:post], :edit_ranking_level=>[:get,:post], :update_ranking_level=>[:get,:post], :delete_ranking_level=>[:get,:post], :ranking_level_cancel=>[:get,:post], :change_priority=>[:get,:post]}
  resources :class_designations
  #resources :exam_reports, :collection => {:course_reports_index=>[:get,:post], :batch_reports_index=>[:get,:post]}
  resources :class_timings
  resources :subjects
  resources :attendances, :collection=>{:daily_register=>:get,:subject_wise_register=>:get}
  resources :employee_attendances
  resources :attendance_reports
  resources :cce_exam_categories
  resources :assessment_scores,:collection=>{:exam_fa_groups=>[:get],:observation_groups=>[:get]}
  resources :cce_settings,:collection=>{:basic=>[:get],:scholastic=>[:get],:co_scholastic=>[:get]}
  resources :scheduled_jobs,:except => [:show]
  resources :fa_groups,:collection=>{:assign_fa_groups=>[:get,:post],:new_fa_criteria=>[:get,:post],:create_fa_criteria=>[:get,:post],:edit_fa_criteria=>[:get,:post],:update_fa_criteria=>[:get,:post],:destroy_fa_criteria=>[:post],:reorder=>[:get,:post]}
  #  do |fa|
  #    fa.resources  :fa_criterias
  #  end
  resources :fa_criterias do 
    resources :descriptive_indicators do 
      resources :assessment_tools
    end
  end
  resources :observations do 
    resources :descriptive_indicators do 
      resources :assessment_tools
    end
  end
  resources :observation_groups,:member=>{:new_observation=>[:get,:post],:create_observation=>[:get,:post],:edit_observation=>[:get,:post],:update_observation=>[:get,:post],:destroy_observation=>[:post],:reorder=>[:get,:post]},:collection=>{:assign_courses=>[:get,:post],:set_observation_group=>[:get,:post]}
  resources :cce_weightages,:member=>{:assign_courses=>[:get,:post]},:collection=>{:assign_weightages=>[:get,:post]}
  resources :cce_grade_sets, :member=>{:new_grade=>[:get,:post],:edit_grade=>[:get,:post],:update_grade=>[:get,:post],:destroy_grade=>[:post]}

  # feed 'courses/manage_course', :controller => 'courses' ,:action=>'manage_course'
  # feed 'courses/manage_batches', :controller => 'courses' ,:action=>'manage_batches'
  resources :courses, :has_many => :batches, :collection => {:grouped_batches=>[:get,:post],:create_batch_group=>[:get,:post],:edit_batch_group=>[:get,:post],:update_batch_group=>[:get,:post],:delete_batch_group=>[:get,:post],:assign_subject_amount => [:get,:post],:edit_subject_amount => [:get,:post],:destroy_subject_amount => [:get,:post]}

  resources :batches, :collection=>{:batches_ajax=>[:get]} do 
    resources :exam_groups
    #batch.resources :additional_exam_groups
    resources :elective_groups, :as => :electives
  end

  resources :exam_groups do 
    resources :exams, :member => { :save_scores => :post }
  end

  #  resources :additional_exam_groups do |additional_exam_group|
  #    additional_exam_group.resources :additional_exams , :member => { :save_additional_scores => :post }
  #  end

  resources :timetables do |timetable|
    resources :timetable_entries
  end

  # fa_scores 'assessment_scores/exam/:exam_id/fa_group/:fa_group_id', :controller=>'assessment_scores',:action=>'fa_scores'
  # observation_scores 'assessment_scores/batch/:batch_id/observation_group/:observation_group_id', :controller=>'assessment_scores',:action=>'observation_scores'
  # scheduled_task 'scheduled_jobs/:job_object/:job_type',:controller => "scheduled_jobs",:action => "index"
  # scheduled_task_object 'scheduled_jobs/:job_object',:controller => "scheduled_jobs",:action => "index"


  #connect 'parts/:number', :controller => 'inventory', :action => 'sho
  # connect ':controller/:action/:id'
  # connect ':controller/:action' 
  # connect ':controller/:action/:id/:id2'
  # connect ':controller/:action/:id.:format'


end

app/models/assessment_tool.rb
#Fedena
#Copyright 2011 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.
class AssessmentTool < ApplicationRecord
#  belongs_to :descriptive_indicator
#  has_many    :assessment_scores
end

app/controllers/assessment_tools_controller.rb
#Fedena
#Copyright 2011 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

class AssessmentToolsController < ApplicationController
  before_action :login_required
  filter_access_to :all
  def index
    @descriptive=DescriptiveIndicator.find(params[:descriptive_indicator_id])
    @assessment_tools=@descriptive.assessment_tools
    @describable=@descriptive.describable
    if @descriptive.describable_type == "Observation"
      @observation_group=@describable.observation_group
    else
      @fa_group=@describable.fa_group
    end
  end

  def new
    @descriptive=DescriptiveIndicator.find(params[:id])
    @assessment_tool=AssessmentTool.new
  end

  def create
    @assessment_tool=AssessmentTool.new(params[:assessment_tool])
    if @assessment_tool.save
      @assessment_tools=@assessment_tool.descriptive_indicator.assessment_tools
      flash[:notice]=t("descriptive_indicator_created")
    else
      @error=true
    end
  end

  def edit
    @assessment_tool=AssessmentTool.find(params[:id])
  end

  def update
    @assessment_tool=AssessmentTool.find(params[:id])
    @assessment_tool.attributes=(params[:assessment_tool])
    if @assessment_tool.save
      @assessment_tools=@assessment_tool.descriptive_indicator.assessment_tools
      flash[:notice]=t("descriptive_indicator_updated")
    else
      @error=true
    end
  end

end

app/views/assessment_tools/_assessment_tools.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<% unless @assessment_tools.empty?  %>
  <table align="center" width="100%" cellpadding="1" cellspacing="1">
    <tr class="tr-head">
      <td><%= t("descriptive_indicators") %></td>
      <td><%= t("desc_text") %></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <% @assessment_tools.each do |g| %>
      <tr class="tr-<%= cycle('odd', 'even') %>">
        <td class="col-1">
          <%= g.name %>
        </td>
        <td class="col-2">
          <%= g.desc %>
        </td>
        <td class="col-3">
          <div class="category-edit">
            <%= link_to_remote "#{t("edit_text")}", :url => { :action => 'edit', :id => g.id },:method=>:get %>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <%= t('no_assessment_tools') %>
<% end %>

app/views/assessment_tools/_edit.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<div id="page-yield">
  <div class="box">
    <% form_remote_for @assessment_tool,:url=>{:controller=>"assessment_tools",:action=>'update',:id=>@assessment_tool.id} do |f| %>
      <div id="form-errors"></div>
      <%= error_messages_for :assessment_tool %>
      <div class="label-field-pair">
        <label for="category_name"><%= t('name') %></label>
        <div class="text-input-bg"><%= f.text_field :name %></div>
      </div>
      <div class="label-field-pair">
        <label for="category_name"><%= t('desc') %></label>
        <div class="text-input-bg"><%= f.text_field :desc %></div>
      </div>
      <%= f.submit "", :value => "► #{t('save')}", :class => "submit_button" %>
    <% end %>
  </div>
</div>

app/views/assessment_tools/_errors.html.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<div id="error-box">
<ul>
  <% errors.errors.each_full do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
</div>

app/views/assessment_tools/_new.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<div id="page-yield">
  <div class="box">
    <% form_remote_for @assessment_tool,:url=>{:controller=>"assessment_tools",:action=>'create'} do |f| %>
      <div id="form-errors"></div>
      <%= error_messages_for :assessment_tool %>
      <div class="label-field-pair">
        <label for="category_name"><%= t('name') %></label>
        <div class="text-input-bg"><%= f.text_field :name %></div>
      </div>
      <div class="label-field-pair">
        <label for="category_name"><%= t('desc') %></label>
        <div class="text-input-bg"><%= f.text_field :desc %></div>
      </div>
      <%= f.hidden_field :descriptive_indicator_id,:value=>@descriptive.id %>
      <%= f.submit "", :value => "► #{t('save')}", :class => "submit_button" %>
    <% end %>
  </div>
</div>

app/views/assessment_tools/index.html.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<div id="content-header">
  <%= stylesheet_link_tag("observation_groups/show.css") %>
  <%= image_tag("/images/examination/show_exam.png") %>
  <h1><%= t('weightages_text') %></h1>
  <h3><%= t('new_text') %></h3>
  <div id="app-back-button">
    <%= link_to_function image_tag("/images/buttons/back.png",:border => 0), "history.back()" %>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <li>
      <%= link_to_remote "#{t('new_text')}", :url => { :action => 'new', :id => @descriptive.id } %>
    </li>
  </ul>
</div>

<div id="page-yield">
  <div id="flash-box">
    <% unless flash[:notice].nil? %>
      <p class="flash-msg"> <%= flash[:notice] %> </p>
    <% end %>
  </div>
  <div class="bread_crumb">
    <% if @descriptive.describable_type == "Observation" %>
      <%= link_to t('observation_groups'), observation_groups_path %> &raquo;
      <%= link_to @observation_group.name, observation_group_path(@observation_group) %> &raquo;
      <%= link_to @describable.name, observation_descriptive_indicators_path(@describable) %> &raquo;
    <% else %>
      <%= link_to t('fa_groups'), fa_groups_path %> &raquo;
      <%= link_to @fa_group.name, fa_group_path(@fa_group) %> &raquo;
      <%= link_to @describable.fa_name, fa_criteria_descriptive_indicators_path(@describable) %> &raquo;
    <% end %>
    <%= @descriptive.name %>
  </div>
  <div class="title">
    <%= t("name") %>
    <div class="description">:&nbsp;&nbsp;&nbsp;<%= @descriptive.name %></div>
  </div>
  <div class="title">
    <%= t("desc_text") %>
    <div class="description">:&nbsp;&nbsp;&nbsp;<%= @descriptive.desc %></div>
  </div>
  <div id="assessment_tools">
    <%= render  :partial=>'assessment_tools' %>
  </div>
  <div id="modal-box" style="display:none;"></div>
</div>