config/routes.rb
Rails.application.routes.draw do

  root :controller => 'user', :action => 'login'
  resources :grading_levels
  resources :ranking_levels, :collection => {:create_ranking_level=>[:get,:post], :edit_ranking_level=>[:get,:post], :update_ranking_level=>[:get,:post], :delete_ranking_level=>[:get,:post], :ranking_level_cancel=>[:get,:post], :change_priority=>[:get,:post]}
  resources :class_designations
  #resources :exam_reports, :collection => {:course_reports_index=>[:get,:post], :batch_reports_index=>[:get,:post]}
  resources :class_timings
  resources :subjects
  resources :attendances, :collection=>{:daily_register=>:get,:subject_wise_register=>:get}
  resources :employee_attendances
  resources :attendance_reports
  resources :cce_exam_categories
  resources :assessment_scores,:collection=>{:exam_fa_groups=>[:get],:observation_groups=>[:get]}
  resources :cce_settings,:collection=>{:basic=>[:get],:scholastic=>[:get],:co_scholastic=>[:get]}
  resources :scheduled_jobs,:except => [:show]
  resources :fa_groups,:collection=>{:assign_fa_groups=>[:get,:post],:new_fa_criteria=>[:get,:post],:create_fa_criteria=>[:get,:post],:edit_fa_criteria=>[:get,:post],:update_fa_criteria=>[:get,:post],:destroy_fa_criteria=>[:post],:reorder=>[:get,:post]}
  #  do |fa|
  #    fa.resources  :fa_criterias
  #  end
  resources :fa_criterias do 
    resources :descriptive_indicators do 
      resources :assessment_tools
    end
  end
  resources :observations do 
    resources :descriptive_indicators do 
      resources :assessment_tools
    end
  end
  resources :observation_groups,:member=>{:new_observation=>[:get,:post],:create_observation=>[:get,:post],:edit_observation=>[:get,:post],:update_observation=>[:get,:post],:destroy_observation=>[:post],:reorder=>[:get,:post]},:collection=>{:assign_courses=>[:get,:post],:set_observation_group=>[:get,:post]}
  resources :cce_weightages,:member=>{:assign_courses=>[:get,:post]},:collection=>{:assign_weightages=>[:get,:post]}
  resources :cce_grade_sets, :member=>{:new_grade=>[:get,:post],:edit_grade=>[:get,:post],:update_grade=>[:get,:post],:destroy_grade=>[:post]}

  # feed 'courses/manage_course', :controller => 'courses' ,:action=>'manage_course'
  # feed 'courses/manage_batches', :controller => 'courses' ,:action=>'manage_batches'
  resources :courses, :has_many => :batches, :collection => {:grouped_batches=>[:get,:post],:create_batch_group=>[:get,:post],:edit_batch_group=>[:get,:post],:update_batch_group=>[:get,:post],:delete_batch_group=>[:get,:post],:assign_subject_amount => [:get,:post],:edit_subject_amount => [:get,:post],:destroy_subject_amount => [:get,:post]}

  resources :batches, :collection=>{:batches_ajax=>[:get]} do 
    resources :exam_groups
    #batch.resources :additional_exam_groups
    resources :elective_groups, :as => :electives
  end

  resources :exam_groups do 
    resources :exams, :member => { :save_scores => :post }
  end

  #  resources :additional_exam_groups do |additional_exam_group|
  #    additional_exam_group.resources :additional_exams , :member => { :save_additional_scores => :post }
  #  end

  resources :timetables do |timetable|
    resources :timetable_entries
  end

  # fa_scores 'assessment_scores/exam/:exam_id/fa_group/:fa_group_id', :controller=>'assessment_scores',:action=>'fa_scores'
  # observation_scores 'assessment_scores/batch/:batch_id/observation_group/:observation_group_id', :controller=>'assessment_scores',:action=>'observation_scores'
  # scheduled_task 'scheduled_jobs/:job_object/:job_type',:controller => "scheduled_jobs",:action => "index"
  # scheduled_task_object 'scheduled_jobs/:job_object',:controller => "scheduled_jobs",:action => "index"


  #connect 'parts/:number', :controller => 'inventory', :action => 'sho
  # connect ':controller/:action/:id'
  # connect ':controller/:action' 
  # connect ':controller/:action/:id/:id2'
  # connect ':controller/:action/:id.:format'


end

app/models/elective_group.rb
#Fedena
#Copyright 2011 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

class ElectiveGroup < ApplicationRecord
  belongs_to :batch
  has_many :subjects

  validates_presence_of :name,:batch_id

  scope :for_batch, lambda { |b| where(:batch_id => b, :is_deleted => false) }

  def inactivate
    update_attribute(:is_deleted, true)
  end
end

app/controllers/elective_groups_controller.rb
#Fedena
#Copyright 2011 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

class ElectiveGroupsController < ApplicationController
  before_action :pre_load_objects
  before_action :login_required
  filter_access_to :all
  def index
    @elective_groups = ElectiveGroup.for_batch(@batch.id).includes(:subjects)
  end

  def new
    @elective_group = @batch.elective_groups.build
  end

  def create
    @elective_group = ElectiveGroup.new(params[:elective_group])
    @elective_group.batch_id = @batch.id
    if @elective_group.save
      flash[:notice] = "#{t('flash1')}"
      redirect_to batch_elective_groups_path(@batch)
    else
      render :action=>'new'
    end
  end

  def edit
    @elective_group = ElectiveGroup.find(params[:id])
    render 'edit'
  end

  def update
    @elective_group = ElectiveGroup.find(params[:id])
    if @elective_group.update_attributes(params[:elective_group])
      flash[:notice] = "#{t('flash3')}"
      #redirect_to [@batch, @elective_group]
      redirect_to batch_elective_groups_path(@batch)
    else
      render 'edit'
    end
  end

  def destroy
    @elective_group.inactivate
    flash[:notice] =  "#{t('flash2')}"
    redirect_to batch_elective_groups_path(@batch)
  end

  def show
    @electives = Subject.where("batch_id = ? AND elective_group_id = ? AND is_deleted =false",@batch.id,@elective_group.id)
  end

  private
  def pre_load_objects
    @batch = Batch.find(params[:batch_id]).includes(:course)
    @course = @batch.course
    @elective_group = ElectiveGroup.find(params[:id]) unless params[:id].nil?
  end
end

app/views/elective_groups/edit.html.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<div id="content-header">
  <%= image_tag("/images/examination/show_exam.png") %>
  <h1><%= t('batches_text') %></h1>
  <h3><%= "#{t('new_elective')}" %></h3>
  <div id="app-back-button">
    <%= link_to_function image_tag("/images/buttons/back.png",:border => 0), "history.back()" %>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <li><%= link_to t('new_text'), new_batch_elective_group_path(@batch) %></li>

  </ul>
</div>
<div id="page-yield">

  <% unless flash[:notice].nil? %>
    <p class="flash-msg"> <%= flash[:notice] %> </p>
  <% end %>

  <div class="bread_crumb">
    <%= link_to t('courses_text'), courses_path %> &raquo;
    <%= link_to @course.full_name, @course %> &raquo;
    <%= link_to "#{t('batch')} #{@batch.name}", [@course, @batch] %> &raquo;
    <%= link_to "#{t('electives')}", batch_elective_groups_path(@batch) %> &raquo;
    <%= t('new_text')   %>
  </div>
  <div class="box">


    <% form_for [@batch, @elective_group] do |f| %>
      <%= f.error_messages :header_message => nil %>

      <div class="label-field-pair">
        <div class="label-container"> <%= f.label "#{t('name')}" %></div>
        <div class="input-container"><%= f.text_field :name %></div>
      </div>

      <%= submit_tag "", :value => "► #{t('save')}", :class => "submit_button" %>

    <% end %>

    <div class="extender"></div>
  </div>
</div>

app/views/elective_groups/index.html.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<div id="content-header">
  <%= image_tag("/images/examination/show_exam.png") %>
  <h1><%= t('batches_text') %></h1>
  <h3><%= "#{t('new_elective')}" %></h3>
  <div id="app-back-button">
    <%= link_to_function image_tag("/images/buttons/back.png",:border => 0), "history.back()" %>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <li><%= link_to t('new_text'), new_batch_elective_group_path(@batch) %></li>

  </ul>
</div>
<div id="page-yield">

  <% unless flash[:notice].nil? %>
    <p class="flash-msg"> <%= flash[:notice] %> </p>
  <% end %>

  <div class="box">

    <div class="bread_crumb">
      <%= link_to t('course_text'), courses_path %> &raquo;
      <%= link_to @course.full_name, @course %> &raquo;
      <%= link_to @batch.name, [@course, @batch] %> &raquo;
      <%= t('elective_group') %>
    </div>


    <ul id="category-list">

      <% @elective_groups.each do |elective| %>
        <li class="list<%=cycle('odd', 'even')%>">
          <div class="category-name"><%= link_to elective.name, [@batch, elective] %></div>
          <div class="category-edit"><%= link_to t('edit_text'),
              :controller=>"elective_groups",:action => "edit", :id =>elective %> </div>
          <% @subjects= Subject.find_all_by_elective_group_id(elective, :conditions => "is_deleted = '0'") %>
          <% if @subjects.empty? %>
            <div class="category-delete"><%= link_to(t('delete_text'), [@batch, elective],
                :method => 'delete',
                :confirm => t('delete_confirm_msg')) %> </div>
          <% end %>
        </li>
      <% end %>

    </ul>

    <div class="extender"></div>
  </div>
</div>

app/views/elective_groups/new.html.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<div id="content-header">
  <%= image_tag("/images/examination/show_exam.png") %>
  <h1><%= t('batches_text') %></h1>
  <h3><%= "#{t('new_elective')}" %></h3>
  <div id="app-back-button">
    <%= link_to_function image_tag("/images/buttons/back.png",:border => 0), "history.back()" %>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <li><%= link_to t('new_text'), new_batch_elective_group_path(@batch) %></li>

  </ul>
</div>
<div id="page-yield">

  <% unless flash[:notice].nil? %>
    <p class="flash-msg"> <%= flash[:notice] %> </p>
  <% end %>

  <div class="bread_crumb">
    <%= link_to t('course_text'), courses_path %> &raquo;
    <%= link_to @course.full_name, @course %> &raquo;
    <%= link_to "#{t('batch')} #{@batch.name}", [@course, @batch] %> &raquo;
    <%= link_to "#{t('electives')}", batch_elective_groups_path(@batch) %> &raquo;
    <%= t('new_text') %>
  </div>
  <div class="box">


    <% form_for [@batch, @elective_group] do |f| %>
      <%= f.error_messages :header_message => nil %>

      <div class="label-field-pair">
        <div class="label-container"> <%= f.label "#{t('name')}" %></div>
        <div class="input-container"><%= f.text_field :name %></div>
      </div>

      <%= submit_tag "", :value => "► #{t('save')}", :class => "submit_button" %>

    <% end %>

    <div class="extender"></div>
  </div>
</div>

app/views/elective_groups/show.html.erb
<%-# Fedena
#Copyright 2010 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing,
#software distributed under the License is distributed on an
#"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#KIND, either express or implied.  See the License for the
#specific language governing permissions and limitations
#under the License. -%>

<div id="content-header">
  <%= image_tag("/images/examination/show_exam.png") %>
  <h1><%= t('batches_text') %></h1>
  <h3><%= "#{t('show_elective')}" %></h3>
  <div id="app-back-button">
    <%= link_to_function image_tag("/images/buttons/back.png",:border => 0), "history.back()" %>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <li><%= link_to_remote  t('add'), :url => { :controller=>"subjects",:action => 'new', :id => @batch,:id2=>@elective_group} %></li>
  </ul>
</div>
<div id="page-yield">
  <div id="flash-box">
    <% unless flash[:notice].nil? %>
      <p class="flash-msg"> <%= flash[:notice] %> </p>
    <% end %>
  </div>
  <div class="bread_crumb">
    <%= link_to t('course_text'), courses_path %> &raquo;
    <%= link_to @course.full_name, @course %> &raquo;
    <%= link_to "#{t('batch')} #{@batch.name}", [@course, @batch] %> &raquo;
    <%= link_to "#{t('electives')}", batch_elective_groups_path(@batch) %> &raquo;
    <%= @elective_group.name %>
  </div>


  <div class="box">


    <div id="subjects">

      <ul id="category-list">
        <% @electives.each do |subject| %>
          <li id="subject-<%= subject.id %>" class="list<%= cycle('even','odd')%>" >
            <div class="category-name"><%= subject.name %></div>
            <div class="category-code"><%= subject.code %></div>
            <div class="category-edit"><%= link_to_remote("#{t('edit_text')} ",
                :url => { :controller=>"subjects",:action => 'edit', :id =>subject,:id2=>@elective_group},
                :method => 'get' ) %> </div>
            <div class="category-delete"><%= link_to_remote("#{t('delete_text')}",
                :url => subject_path(subject),
                :method => 'delete',
                :confirm => t('delete_confirm_msg'),
                :update => "subject-#{subject.id}") %> </div>
            <div class="category-assign"><%= link_to " #{t('assign_student')}", :controller=>"student", :action=>"electives",:id=>@batch,:id2=>subject.id%>
            </div>
          </li>
        <% end %>
      </ul>

    </div>
    <div id="modal-box" style="display:none;"></div>


    <div class="extender"></div>
  </div>
</div>